sudo: false

language: haskell

matrix:
  include:
    - env: BUILD=stack ARGS="--resolver lts-9" GHCVER=8.0.2
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: BUILD=stack ARGS="--resolver lts-10" GHCVER=8.2.2
      compiler: ": #stack 8.2.2"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: BUILD=stack ARGS="--resolver nightly" GHCVER=head
      compiler: ": #stack nightly"
      addons: {apt: {packages: [libgmp-dev]}}
  allow_failures:
    - env: BUILD=stack ARGS="--resolver nightly"

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 -  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - stack config set system-ghc --global true
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

script:
 - stack --no-terminal --skip-ghc-check --haddock test

cache:
 directories:
  - $HOME/.stack
  - $HOME/.ghc
  - $HOME/.cabal
