ghc:
 - 8.0.2

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 -  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - stack config set system-ghc --global true
 - export PATH=/opt/ghc/8.0.2/bin:$PATH

script:
 - stack --no-terminal --skip-ghc-check --haddock test

cache:
 directories:
  - $HOME/.stack
