name: confide
version: '0.1.0.3'
category: Data
synopsis: derive typeclass instances for decoding types from HOCON conf
author: Alex Milkov
maintainer: amilkov3@gmail.com
copyright: 2018 Alex Milkov
license: BSD3
github: amilkov3/confide
homepage: https://github.com/amilkov3/confide
default-extensions:
- DefaultSignatures
- DeriveGeneric
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- TypeOperators
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Confide
  - Data.Confide.Generic
  dependencies:
  - base >=4.7 && <5
  - deiko-config >= 0.5.0.1
  - exceptions
  - text
tests:
  confide-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - confide
    - deiko-config
    - tasty
    - tasty-hunit
    - text
