name: confide
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/confide
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Confide
  - Data.Confide.Generic
  dependencies:
  - base >=4.7 && <5
  - deiko-config
  - exceptions
  - text
tests:
  confide-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - confide
    - deiko-config
    - tasty
    - tasty-hunit
    - text
