name: confide
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/confide
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Config
  - Data.Config.Generic
  dependencies:
  - base >=4.7 && <5
  - array
  - mtl
  - parsec
  - text
  - transformers
  - containers
  - exceptions
executables:
  confide-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - confide
tests:
  confide-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - confide
    - tasty
    - tasty-hunit
    - text
